export const pakistanProvinces = [
  "Punjab",
  "Sindh",
  "Khyber Pakhtunkhwa",
  "Balochistan",
  "Islamabad Capital Territory",
  "Gilgit-Baltistan",
  "Azad Jammu and Kashmir",
] as const;

export type PakistanProvince = (typeof pakistanProvinces)[number];

export const pakistanCitiesByProvince: Record<PakistanProvince, string[]> = {
  Punjab: [
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Multan",
    "Gujranwala",
    "Sialkot",
    "Sargodha",
    "Bahawalpur",
    "Sheikhupura",
    "Rahim Yar Khan",
    "Jhang",
    "Dera Ghazi Khan",
    "Gujrat",
    "Sahiwal",
    "Okara",
    "Wah Cantt",
    "Kasur",
    "Chiniot",
    "Kamoke",
    "Mandi Bahauddin",
    "Jhelum",
    "Khanewal",
    "Hafizabad",
    "Muzaffargarh",
    "Khanpur",
    "Gojra",
    "Bahawalnagar",
    "Muridke",
    "Pakpattan",
    "Toba Tek Singh",
    "Vehari",
    "Mianwali",
    "Chakwal",
    "Bhakkar",
    "Lodhran",
    "Attock",
    "Narowal",
    "Burewala",
    "Jaranwala",
    "Samundri",
  ],
  Sindh: [
    "Karachi",
    "Hyderabad",
    "Sukkur",
    "Larkana",
    "Nawabshah",
    "Mirpur Khas",
    "Jacobabad",
    "Shikarpur",
    "Khairpur",
    "Dadu",
    "Tando Allahyar",
    "Tando Adam",
    "Thatta",
    "Badin",
    "Ghotki",
    "Umerkot",
    "Moro",
    "Kandhkot",
    "Naushahro Feroze",
    "Jamshoro",
  ],
  "Khyber Pakhtunkhwa": [
    "Peshawar",
    "Mardan",
    "Mingora",
    "Kohat",
    "Dera Ismail Khan",
    "Abbottabad",
    "Mansehra",
    "Swabi",
    "Nowshera",
    "Charsadda",
    "Bannu",
    "Haripur",
    "Chitral",
    "Karak",
    "Lakki Marwat",
    "Hangu",
    "Timergara",
    "Batkhela",
    "Tank",
  ],
  Balochistan: [
    "Quetta",
    "Turbat",
    "Khuzdar",
    "Chaman",
    "Gwadar",
    "Hub",
    "Sibi",
    "Zhob",
    "Dera Murad Jamali",
    "Dera Allah Yar",
    "Pishin",
    "Loralai",
    "Mastung",
    "Kalat",
    "Nushki",
    "Kharan",
  ],
  "Islamabad Capital Territory": ["Islamabad"],
  "Gilgit-Baltistan": [
    "Gilgit",
    "Skardu",
    "Hunza",
    "Chilas",
    "Ghanche",
    "Ghizer",
    "Astore",
    "Khaplu",
    "Nagar",
  ],
  "Azad Jammu and Kashmir": [
    "Muzaffarabad",
    "Mirpur",
    "Kotli",
    "Rawalakot",
    "Bagh",
    "Bhimber",
    "Hattian Bala",
    "Neelum",
    "Pallandri",
  ],
};

export const pakistanCities = Object.values(pakistanCitiesByProvince)
  .flat()
  .sort((a, b) => a.localeCompare(b));

export const getCitiesForProvince = (province: string) => {
  if (province && province in pakistanCitiesByProvince) {
    return pakistanCitiesByProvince[province as PakistanProvince];
  }

  return pakistanCities;
};
